fybrik:
  target: dremio
  outputs:
    dremio:
      type: dremio
      user: admin
      user_ssl: 'false'
      password: null
      software_host: host.docker.internal
      port: 8080
      threads: 1
