# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: app.fybrik.io/v1beta1
kind: FybrikModule
metadata:
  name: read
  namespace: fybrik-system
spec:
  chart:
    name: ghcr.io/mohammad-nassar10/dbt-module-chart:0.0.0
  type: service
  capabilities:
    - capability: read
      api:
          connection:
            name: dbt
            dbt:
              hostname: "{{ .Release.Name }}.{{ .Release.Namespace }}"
              port: 8580
              scheme: grpc
      supportedInterfaces: 
      - source:
          protocol: trino
          dataformat: iceberg
      - source:
          protocol: dremio
          dataformat: iceberg

      actions:
        - name: RedactAction
        - name: RemoveAction
