apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: dataset1
spec:
  secretRef: 
    name: dataset1
  details:
    dataFormat: iceberg
    connection:
      name: trino
      trino:
        host: "host.docker.internal"
        port: 8080
        catalog: "iceberg"
        schema: "icebergtrino"
  metadata:
    name: "Data Asset"
    geography: theshire
    tags:
      finance: true
    columns:
      - name: custkey
        tags:
          PII: true
